#!/bin/bash
source config

# special case; if "edit", drop into editing links file
if [[ "$1" = "edit" ]]
then
    cd $DIR
    $GNEDITOR links
    $PYTHON links.py updatemf
    exit 0
fi

filepath=
title=
notebook=

usage()
{
cat << EOF
Usage:
    `basename $0` -f FILE -t TITLE -b NOTEBOOK

Alternate usage (to edit links directly):
    `basename $0` edit
EOF
}

while getopts "f:t:b:" OPTION; do
    case $OPTION in
        f)
            filepath=$(abspath "$OPTARG")
            ;;
        t)
            title=$OPTARG
            ;;
        b)
            notebook=$OPTARG
            ;;
    esac
done

if [[ -z $filepath ]] || [[ -z $title ]] || [[ -z $notebook ]]
then
    usage
    exit 1
fi

$GEEKNOTE create --title "$title" --notebook "$notebook" --content "$filepath"

cd $DIR
echo "$filepath|$notebook|$title" >> links

$PYTHON links.py updatemf
