#!/bin/bash
source config

usage()
{
cat << EOF
Usage:
    `basename $0` -f FILE -t TITLE -b NOTEBOOK [OPTIONS]

Options:
    -e   link FILE to existing note

Alternate usage (to edit links directly):
    `basename $0` edit
EOF
}

# special case; if "edit", drop into editing links file
if [[ "$1" = "edit" ]]
then
    cd $DIR
    $GNEDITOR links
    $PYTHON links.py updatemf
    exit 0
fi

filepath=
title=
notebook=
createnew=true
while getopts "f:t:b:e" OPTION; do
    case $OPTION in
        f)
            filepath=$(abspath "$OPTARG")
            ;;
        t)
            title=$OPTARG
            ;;
        b)
            notebook=$OPTARG
            ;;
        e)
            createnew=false
            ;;
    esac
done

if [[ -z $filepath ]] || [[ -z $title ]] || [[ -z $notebook ]]
then
    usage
    exit 1
fi

if [ $createnew = true ]; then
    echo "Creating new note"
    echo -e "\tName: $title"
    echo -e "\tNotebook: $notebook"
    echo -e "\tContents: $filepath"
    $GEEKNOTE create --title "$title" --notebook "$notebook" --content "$filepath"
else
    echo "Linked to existing note"
    echo -e "\tName: $title"
    echo -e "\tNotebook: $notebook"
    echo -e "\tFile: $filepath"
fi

cd $DIR
echo "$filepath|$notebook|$title" >> links

$PYTHON links.py updatemf
